-- MySQL Script generated by MySQL Workbench
-- Sat Mar 26 16:55:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`administrateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`administrateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`administrateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(40) NOT NULL,
  `prenom` VARCHAR(30) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `mot_de_passe` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`consultant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`consultant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`consultant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(40) NOT NULL,
  `prenom` VARCHAR(30) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `mot_de_passe` VARCHAR(40) NOT NULL,
  `id_administrateur` INT NOT NULL,
  PRIMARY KEY (`id`, `id_administrateur`),
  INDEX `fk_consultant_administrateur_idx` (`id_administrateur` ASC) VISIBLE,
  CONSTRAINT `fk_consultant_administrateur`
    FOREIGN KEY (`id_administrateur`)
    REFERENCES `mydb`.`administrateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`recruteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recruteur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recruteur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(60) NOT NULL,
  `pass` VARCHAR(20) NOT NULL,
  `nom` VARCHAR(40) NOT NULL,
  `prenom` VARCHAR(40) NOT NULL,
  `entreprise_nom` VARCHAR(100) NOT NULL,
  `entreprise_adresse` VARCHAR(60) NULL,
  `entreprise_code_postal` VARCHAR(5) NULL,
  `entreprise_ville` VARCHAR(45) NULL,
  `id_consultant` INT NOT NULL,
  PRIMARY KEY (`id`, `id_consultant`),
  INDEX `fk_recruteur_consultant1_idx` (`id_consultant` ASC) VISIBLE,
  CONSTRAINT `fk_recruteur_consultant1`
    FOREIGN KEY (`id_consultant`)
    REFERENCES `mydb`.`consultant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`annonce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`annonce` ;

CREATE TABLE IF NOT EXISTS `mydb`.`annonce` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `intitule` VARCHAR(100) NOT NULL,
  `poste` VARCHAR(50) NOT NULL,
  `ville` VARCHAR(50) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `date` DATE NULL,
  `validation` TINYINT NULL DEFAULT 0,
  `id_recruteur` INT NOT NULL,
  `id_consultant` INT NOT NULL,
  PRIMARY KEY (`id`, `id_recruteur`, `id_consultant`),
  INDEX `fk_annonce_consultant1_idx` (`id_consultant` ASC) VISIBLE,
  INDEX `fk_annonce_recruteur1_idx` (`id_recruteur` ASC) VISIBLE,
  CONSTRAINT `fk_annonce_consultant1`
    FOREIGN KEY (`id_consultant`)
    REFERENCES `mydb`.`consultant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annonce_recruteur1`
    FOREIGN KEY (`id_recruteur`)
    REFERENCES `mydb`.`recruteur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`candidat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`candidat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`candidat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(60) NOT NULL,
  `pass` VARCHAR(20) NOT NULL,
  `nom` VARCHAR(40) NOT NULL,
  `prenom` VARCHAR(40) NOT NULL,
  `cv` VARCHAR(100) NULL DEFAULT NULL,
  `id_consultant` INT NOT NULL,
  PRIMARY KEY (`id`, `id_consultant`),
  INDEX `fk_candidat_consultant1_idx` (`id_consultant` ASC) VISIBLE,
  CONSTRAINT `fk_candidat_consultant1`
    FOREIGN KEY (`id_consultant`)
    REFERENCES `mydb`.`consultant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`candidature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`candidature` ;

CREATE TABLE IF NOT EXISTS `mydb`.`candidature` (
  `candidat_id` INT NOT NULL,
  `annonce_id` INT NOT NULL,
  `id_consultant_approbation` INT NULL,
  PRIMARY KEY (`candidat_id`, `annonce_id`),
  INDEX `fk_candidature_annonce1_idx` (`annonce_id` ASC) VISIBLE,
  CONSTRAINT `fk_candidature_candidat1`
    FOREIGN KEY (`candidat_id`)
    REFERENCES `mydb`.`candidat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidature_annonce1`
    FOREIGN KEY (`annonce_id`)
    REFERENCES `mydb`.`annonce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
